"""add restore code model

Revision ID: 0327e6514cdc
Revises: 52b6e800a97b
Create Date: 2025-08-13 15:27:04.802197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0327e6514cdc'
down_revision = '52b6e800a97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restore_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creds_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creds_id'], ['credentials.key_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restore_code')
    # ### end Alembic commands ###
