"""refactor user table

Revision ID: 29d7ff586f2d
Revises: 44107be86ff6
Create Date: 2025-07-08 16:57:42.009190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d7ff586f2d'
down_revision = '44107be86ff6'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sign_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'gender',
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Integer(),
            existing_nullable=True,
            postgresql_using=(
                "CASE "
                "WHEN gender = 'male' THEN 1 "
                "WHEN gender = 'female' THEN 2 "
                "WHEN gender = 'non-binary' THEN 3 "
                "ELSE NULL END"
            )
        )
        batch_op.create_foreign_key(None, 'zodiac_sign', ['sign_id'], ['sign_id'])
        batch_op.create_foreign_key(None, 'gender', ['gender'], ['gender_id'])
        batch_op.drop_column('zodiac_sign')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zodiac_sign', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('gender',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('sign_id')

    # ### end Alembic commands ###
