"""add gender field tothe  preference table

Revision ID: 44107be86ff6
Revises: a1116936b509
Create Date: 2025-07-08 15:45:40.218863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44107be86ff6'
down_revision = 'a1116936b509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'gender', ['gender_id'], ['gender_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_preferences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gender_id')

    # ### end Alembic commands ###
