"""empty message

Revision ID: 53a6825ba3bc
Revises: d666cc40a281
Create Date: 2025-11-17 00:25:04.212403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a6825ba3bc'
down_revision = 'd666cc40a281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('like_to_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['to_user_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('like_to_user_id_fkey'), 'users', ['to_user_id'], ['user_id'])

    # ### end Alembic commands ###
