"""add preference interest

Revision ID: 64b14093081e
Revises: 29d7ff586f2d
Create Date: 2025-07-11 15:27:56.431621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b14093081e'
down_revision = '29d7ff586f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference_interest',
    sa.Column('preference_interest_id', sa.Integer(), nullable=False),
    sa.Column('preference_id', sa.Integer(), nullable=True),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interest_id'], ['interest.interest_id'], ),
    sa.ForeignKeyConstraint(['preference_id'], ['partner_preferences.preference_id'], ),
    sa.PrimaryKeyConstraint('preference_interest_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preference_interest')
    # ### end Alembic commands ###
