"""add images table

Revision ID: 798c0286ee0e
Revises: f19d0f74713e
Create Date: 2025-07-08 12:49:54.809034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798c0286ee0e'
down_revision = 'f19d0f74713e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_images',
    sa.Column('user_image_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_images')
    # ### end Alembic commands ###
