"""add new columns to meeting table

Revision ID: b28477f0e2e5
Revises: a543970aaeee
Create Date: 2025-07-24 13:32:30.160041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28477f0e2e5'
down_revision = 'a543970aaeee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user1_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user2_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('archived')
        batch_op.drop_column('user2_comment')
        batch_op.drop_column('user1_comment')

    # ### end Alembic commands ###
