"""add cascade delete

Revision ID: d666cc40a281
Revises: b3827974dd39
Create Date: 2025-08-25 22:06:56.029091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd666cc40a281'
down_revision = 'b3827974dd39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('credentials_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('dislike', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('dislike_to_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('dislike_from_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['to_user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['from_user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('like_from_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['from_user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('matches_user1_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('matches_user2_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user1_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user2_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('meeting_feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('meeting_feedbacks_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('meetings_user2_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('meetings_user1_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user2_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user1_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('partner_preferences', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('partner_preferences_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('preference_interest', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('preference_interest_preference_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'partner_preferences', ['preference_id'], ['preference_id'], ondelete='CASCADE')

    with op.batch_alter_table('preference_signs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('preference_signs_preference_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'partner_preferences', ['preference_id'], ['preference_id'], ondelete='CASCADE')

    with op.batch_alter_table('refusals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('refusals_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_images_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('user_interest', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_interest_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_interest_user_id_fkey'), 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_images_user_id_fkey'), 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('refusals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('refusals_user_id_fkey'), 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('preference_signs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('preference_signs_preference_id_fkey'), 'partner_preferences', ['preference_id'], ['preference_id'])

    with op.batch_alter_table('preference_interest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('preference_interest_preference_id_fkey'), 'partner_preferences', ['preference_id'], ['preference_id'])

    with op.batch_alter_table('partner_preferences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('partner_preferences_user_id_fkey'), 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('meetings_user1_id_fkey'), 'users', ['user1_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('meetings_user2_id_fkey'), 'users', ['user2_id'], ['user_id'])

    with op.batch_alter_table('meeting_feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('meeting_feedbacks_user_id_fkey'), 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('matches_user2_id_fkey'), 'users', ['user2_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('matches_user1_id_fkey'), 'users', ['user1_id'], ['user_id'])

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('like_from_user_id_fkey'), 'users', ['from_user_id'], ['user_id'])

    with op.batch_alter_table('dislike', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('dislike_from_user_id_fkey'), 'users', ['from_user_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('dislike_to_user_id_fkey'), 'users', ['to_user_id'], ['user_id'])

    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('credentials_user_id_fkey'), 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
