"""add zodiac and preference_sign tables

Revision ID: e47f9fc1260f
Revises: f084a9bccc9d
Create Date: 2025-07-08 15:22:58.867909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47f9fc1260f'
down_revision = 'f084a9bccc9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zodiac_sign',
    sa.Column('sign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sign_id')
    )
    op.create_table('preference_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preference_id', sa.Integer(), nullable=False),
    sa.Column('sign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['preference_id'], ['partner_preferences.preference_id'], ),
    sa.ForeignKeyConstraint(['sign_id'], ['zodiac_sign.sign_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preference_signs')
    op.drop_table('zodiac_sign')
    # ### end Alembic commands ###
