"""add zodiac and preference_sign tables

Revision ID: f084a9bccc9d
Revises: 798c0286ee0e
Create Date: 2025-07-08 15:21:22.758151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f084a9bccc9d'
down_revision = '798c0286ee0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_preferences', schema=None) as batch_op:
        batch_op.drop_column('zodiac_signs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zodiac_signs', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
