"""add token to restore code

Revision ID: f3d79517174f
Revises: 0327e6514cdc
Create Date: 2025-08-14 12:13:29.308769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d79517174f'
down_revision = '0327e6514cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restore_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restore_code', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###
