"""add compatibilities

Revision ID: fde49cd9ace1
Revises: 0b948e31324a
Create Date: 2025-08-02 20:52:26.762619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde49cd9ace1'
down_revision = '0b948e31324a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zodiac_compatibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sign1_id', sa.Integer(), nullable=True),
    sa.Column('sign2_id', sa.Integer(), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sign1_id'], ['zodiac_sign.sign_id'], ),
    sa.ForeignKeyConstraint(['sign2_id'], ['zodiac_sign.sign_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zodiac_compatibility')
    # ### end Alembic commands ###
